/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

/**
 *
 * @author Suenlie
 */
import javax.swing.*;

public class AdventureMap extends javax.swing.JFrame {

    /**
     * Creates new form AdventureMap
     */
    public AdventureMap() {
        initComponents();
    }
    String name;
    int slp;
    int count =1;
    int stage;
    public AdventureMap(String name, int slp,int stage) {
        this.name = name;
        this.slp = slp;
        this.stage = stage;
        initComponents();
        adventuremap();
        jaialaiBtn.setBackground(new java.awt.Color(0,0,0,0));
        shopwiseBtn.setBackground(new java.awt.Color(0,0,0,0));
        starmallBtn.setBackground(new java.awt.Color(0,0,0,0));
        returnBtn.setBackground(new java.awt.Color(0,0,0,0));
        startBtn.setBackground(new java.awt.Color(0,0,0,0));
        
        mapSetUp();
    }

    public void adventuremap(){
        if(count == 1){
            jaialai.setVisible(true);
            shopwise.setVisible(false);
            starmall.setVisible(false);
        }else if(count == 2){
            jaialai.setVisible(false);
            shopwise.setVisible(true);
            starmall.setVisible(false);
        }else if(count == 3){
            jaialai.setVisible(false);
            shopwise.setVisible(false);
            starmall.setVisible(true);
        }
    }
    
    public void mapSetUp(){
        if(stage == 1){
            crossed.setVisible(true);
            crossed1.setVisible(true);
            shopwiseBtn.setEnabled(false); // Disable shopwiseBtn if stage is 1
            starmallBtn.setEnabled(false); // Disable starmallBtn if stage is 1
        } else if(stage == 2){
            crossed.setVisible(false);
            crossed1.setVisible(true);
            shopwiseBtn.setEnabled(true); // Enable shopwiseBtn if stage is 2
            starmallBtn.setEnabled(false); // Disable starmallBtn if stage is 2
        } else if(stage == 3){
            crossed.setVisible(false);
            crossed1.setVisible(false);
            shopwiseBtn.setEnabled(true); // Disable shopwiseBtn if stage is 3
            starmallBtn.setEnabled(true); // Enable starmallBtn if stage is 3
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crossed1 = new javax.swing.JLabel();
        crossed = new javax.swing.JLabel();
        startBtn = new javax.swing.JButton();
        returnBtn = new javax.swing.JButton();
        starmallBtn = new javax.swing.JButton();
        shopwiseBtn = new javax.swing.JButton();
        jaialaiBtn = new javax.swing.JButton();
        lblBeast = new javax.swing.JLabel();
        lblAqua = new javax.swing.JLabel();
        lblReptile = new javax.swing.JLabel();
        jaialai = new javax.swing.JLabel();
        shopwise = new javax.swing.JLabel();
        starmall = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crossed1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/cards/cross.png"))); // NOI18N
        getContentPane().add(crossed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 160, 160));

        crossed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/cards/cross.png"))); // NOI18N
        getContentPane().add(crossed, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 160, 160));

        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });
        getContentPane().add(startBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 250, 70));

        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });
        getContentPane().add(returnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 80));

        starmallBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starmallBtnActionPerformed(evt);
            }
        });
        getContentPane().add(starmallBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, 150, 130));

        shopwiseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopwiseBtnActionPerformed(evt);
            }
        });
        getContentPane().add(shopwiseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 160, 160));

        jaialaiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaialaiBtnActionPerformed(evt);
            }
        });
        getContentPane().add(jaialaiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 110));

        lblBeast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/beastfinal (1).gif"))); // NOI18N
        getContentPane().add(lblBeast, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 170, 110));

        lblAqua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/aquafinels.gif"))); // NOI18N
        getContentPane().add(lblAqua, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 170, 130));

        lblReptile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/reptile-ezgif.com-resize.gif"))); // NOI18N
        getContentPane().add(lblReptile, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 130, 90));

        jaialai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/backgrounds/GAISANO JAI-ALAI.png"))); // NOI18N
        getContentPane().add(jaialai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        shopwise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/backgrounds/shopWise.png"))); // NOI18N
        getContentPane().add(shopwise, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        starmall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/backgrounds/starMall.png"))); // NOI18N
        getContentPane().add(starmall, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jaialaiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaialaiBtnActionPerformed
        // TODO add your handling code here:
        count = 1;
        stage = 1;
        adventuremap();
    }//GEN-LAST:event_jaialaiBtnActionPerformed

    private void shopwiseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopwiseBtnActionPerformed
        // TODO add your handling code here:
        count = 2;
        stage = 2;
        adventuremap();
    }//GEN-LAST:event_shopwiseBtnActionPerformed

    private void starmallBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starmallBtnActionPerformed
        // TODO add your handling code here:
        count = 3;
        stage = 3;
        adventuremap();
    }//GEN-LAST:event_starmallBtnActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
        new Dashboard(name,slp,stage).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnBtnActionPerformed

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        // TODO add your handling code here:
        new VS(name,slp,stage).setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_startBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdventureMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdventureMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdventureMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdventureMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdventureMap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel crossed;
    private javax.swing.JLabel crossed1;
    private javax.swing.JLabel jaialai;
    private javax.swing.JButton jaialaiBtn;
    private javax.swing.JLabel lblAqua;
    private javax.swing.JLabel lblBeast;
    private javax.swing.JLabel lblReptile;
    private javax.swing.JButton returnBtn;
    private javax.swing.JLabel shopwise;
    private javax.swing.JButton shopwiseBtn;
    private javax.swing.JLabel starmall;
    private javax.swing.JButton starmallBtn;
    private javax.swing.JButton startBtn;
    // End of variables declaration//GEN-END:variables
}
