/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/**
 *
 * @author Suenlie
 */
public class Adventure extends javax.swing.JFrame {

    /**
     * Creates new form Adventure
     */
    
    int countRound=1;
    String filepath = "C:\\Users\\Suenlie\\Downloads\\Axie Infinity - Arena Theme Song.wav";
    
    public Adventure() {
        initComponents();
        PlayMusic(filepath);
        roundCounter.setText("Round "+countRound);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundCounter = new javax.swing.JLabel();
        energyCounter = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundCounter.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        roundCounter.setForeground(new java.awt.Color(255, 255, 255));
        roundCounter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(roundCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 460, 40));

        energyCounter.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        energyCounter.setForeground(new java.awt.Color(255, 255, 255));
        energyCounter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        energyCounter.setText("3/10");
        getContentPane().add(energyCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/Adventurewithanimation.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adventure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adventure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adventure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adventure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adventure().setVisible(true);
            }
        });
    }
    
    public static Clip PlayMusic(String location) {
        try {
            File musicPath = new File(location);
            if (musicPath.exists()) {
                AudioInputStream audioInput = AudioSystem.getAudioInputStream(musicPath);
                Clip clip = AudioSystem.getClip();
                clip.open(audioInput);
                clip.start();
                return clip; // Return the Clip object
            } else {
                System.out.println("Can't find file");
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return null;
    }   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel energyCounter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel roundCounter;
    // End of variables declaration//GEN-END:variables
}
