/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

/**
 *
 * @author Suenlie
 */
import java.awt.Color;
import javax.swing.*;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

public class Dashboard extends javax.swing.JFrame {


    /**
     * Creates new form Dashboard
     */
    private Clip musicClip;
    
    int slp;
    String name;
    public Dashboard() {
        initComponents();
        
    }
    
    String filepath = "C:\\Users\\Suenlie\\Downloads\\axiemusic.wav";
    int stage;
    public Dashboard(String name, int slp, int stage){
        initComponents();
        this.stage = stage;
        this.name = name;
        this.slp = slp;
        musicClip = PlayMusic(filepath);
        txtDisplayName.setText(name);
        btnAdventure.setBackground(new java.awt.Color(0,0,0,0));
        btnArena.setBackground(new java.awt.Color(0,0,0,0));
        btnInventory.setBackground(new java.awt.Color(0,0,0,0));
        btnLeaderboard.setBackground(new java.awt.Color(0,0,0,0));
    }
    
    public Dashboard(String name, int slp,int stage,int ms){
        initComponents();
        this.stage = stage;
        this.name = name;
        this.slp = slp;
        txtDisplayName.setText(name);
        btnAdventure.setBackground(new java.awt.Color(0,0,0,0));
        btnArena.setBackground(new java.awt.Color(0,0,0,0));
        btnInventory.setBackground(new java.awt.Color(0,0,0,0));
        btnLeaderboard.setBackground(new java.awt.Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDisplayName = new javax.swing.JLabel();
        btnAdventure = new javax.swing.JButton();
        btnArena = new javax.swing.JButton();
        btnInventory = new javax.swing.JButton();
        btnLeaderboard = new javax.swing.JButton();
        lblreptile = new javax.swing.JLabel();
        lblbeast = new javax.swing.JLabel();
        lblaqua = new javax.swing.JLabel();
        dashboardBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDisplayName.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        txtDisplayName.setForeground(new java.awt.Color(255, 255, 255));
        txtDisplayName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txtDisplayName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 260, 120));

        btnAdventure.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdventure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdventureMouseEntered(evt);
            }
        });
        btnAdventure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdventureActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdventure, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 200, 90));

        btnArena.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnArena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArenaActionPerformed(evt);
            }
        });
        getContentPane().add(btnArena, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 200, 90));

        btnInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 200, 90));

        btnLeaderboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLeaderboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaderboardActionPerformed(evt);
            }
        });
        getContentPane().add(btnLeaderboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, 200, 90));

        lblreptile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/reptile-ezgif.com-resize.gif"))); // NOI18N
        lblreptile.setText("jLabel1");
        getContentPane().add(lblreptile, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 140, 100));

        lblbeast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/beastfinal (1).gif"))); // NOI18N
        getContentPane().add(lblbeast, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 170, 140));

        lblaqua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/aquafinels.gif"))); // NOI18N
        getContentPane().add(lblaqua, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 170, 130));

        dashboardBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/backgrounds/WAKBALOS.png"))); // NOI18N
        getContentPane().add(dashboardBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArenaActionPerformed
        // TODO add your handling code here:
        String btnsound = "C:\\Users\\Suenlie\\Downloads\\Menu Game Button Click Sound Effect.wav";
        PlayMusic(btnsound);
        new Wakbalos(name, slp,stage).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnArenaActionPerformed

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
        // TODO add your handling code here:
        String btnsound = "C:\\Users\\Suenlie\\Downloads\\Menu Game Button Click Sound Effect.wav";
        PlayMusic(btnsound);
        INVENTORY inventory = new INVENTORY(name,slp,stage);
        inventory.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnInventoryActionPerformed

    private void btnLeaderboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaderboardActionPerformed
        // TODO add your handling code here:
        new Leaderboards(name,slp,stage).setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnLeaderboardActionPerformed

    private void btnAdventureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdventureActionPerformed
        // TODO add your handling code here:
        if (musicClip != null && musicClip.isRunning()) {
            musicClip.stop();
        }
        new AdventureMap(name,slp,stage).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAdventureActionPerformed

    private void btnAdventureMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdventureMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAdventureMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }
    
    public static Clip PlayMusic(String location) {
        try {
            File musicPath = new File(location);
            if (musicPath.exists()) {
                AudioInputStream audioInput = AudioSystem.getAudioInputStream(musicPath);
                Clip clip = AudioSystem.getClip();
                clip.open(audioInput);
                clip.start();
                return clip; // Return the Clip object
            } else {
                System.out.println("Can't find file");
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return null;
    }   
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdventure;
    private javax.swing.JButton btnArena;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnLeaderboard;
    private javax.swing.JLabel dashboardBackground;
    private javax.swing.JLabel lblaqua;
    private javax.swing.JLabel lblbeast;
    private javax.swing.JLabel lblreptile;
    public javax.swing.JLabel txtDisplayName;
    // End of variables declaration//GEN-END:variables
}
