/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

/**
 *
 * @author Suenlie
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


public class Leaderboards extends javax.swing.JFrame {

    /**
     * Creates new form Leaderboards
     */
    public Leaderboards() {
        initComponents();
    }
    
    String name;
    int slp,stage;
     Connection con = null;
     Statement st = null;
     ResultSet rs = null;
    
    public Leaderboards(String name, int slp, int stage) {
        initComponents();
        returnBtn.setBackground(new java.awt.Color(0,0,0,0));
        this.name = name;
        this.slp = slp;
        this.stage = stage;
        
        try {
            // Establishing a connection
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/wakbalo", "root", "");
            
            // SQL query to fetch the "name" column from the "userprof" table
            String sql = "SELECT * FROM userprof ORDER BY slp desc";
            
            // Creating a statement
            st = con.createStatement();
            
            // Executing the query
            rs = st.executeQuery(sql);
            int row = 1;
            // Iterating through the result set and printing the names
            while (rs.next()) {
                if(row == 1){
                    String lname = rs.getString("name");
                    lblname1.setText(lname);
                    int stage1 = rs.getInt("stage");
                    lblRank1.setText(""+stage1);
                    int slp1 = rs.getInt("slp");
                    lblslp1.setText(""+slp1);
                }else if(row == 2){
                    String lname2 = rs.getString("name");
                    lblname2.setText(lname2);
                    int stage2 = rs.getInt("stage");
                    lblRank2.setText(""+stage2);
                    int slp2 = rs.getInt("slp");
                    lblslp2.setText(""+slp2);
                }else if(row == 3){
                    String lname3 = rs.getString("name");
                    lblname3.setText(lname3);
                    int stage3 = rs.getInt("stage");
                    lblRank3.setText(""+stage3);
                    int slp3 = rs.getInt("slp");
                    lblslp3.setText(""+slp3);
                }
                row++;
            }
        } catch (ClassNotFoundException | SQLException ex) {
            // Handling exceptions
            ex.printStackTrace();
        }
        
    }
    
    public String getName(){
        return name;
    }
    
    public int getSlp(){
        return slp;
    }
    
    public int getStage(){
        return stage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnBtn = new javax.swing.JButton();
        lblslp3 = new javax.swing.JLabel();
        lblslp2 = new javax.swing.JLabel();
        lblslp1 = new javax.swing.JLabel();
        lblRank3 = new javax.swing.JLabel();
        lblRank2 = new javax.swing.JLabel();
        lblRank1 = new javax.swing.JLabel();
        lblname3 = new javax.swing.JLabel();
        lblname2 = new javax.swing.JLabel();
        lblname1 = new javax.swing.JLabel();
        lblLeaderboard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });
        getContentPane().add(returnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 70));
        getContentPane().add(lblslp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, 80, 20));
        getContentPane().add(lblslp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 80, 20));
        getContentPane().add(lblslp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 80, 20));
        getContentPane().add(lblRank3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 90, 20));
        getContentPane().add(lblRank2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 90, 20));
        getContentPane().add(lblRank1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 90, 20));
        getContentPane().add(lblname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 50, 20));
        getContentPane().add(lblname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 50, 20));
        getContentPane().add(lblname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 80, 20));

        lblLeaderboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/backgrounds/Leaderboardfinal (1).png"))); // NOI18N
        getContentPane().add(lblLeaderboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
        new Dashboard(name,slp,stage,0).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Leaderboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Leaderboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Leaderboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Leaderboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Leaderboards().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLeaderboard;
    private javax.swing.JLabel lblRank1;
    private javax.swing.JLabel lblRank2;
    private javax.swing.JLabel lblRank3;
    private javax.swing.JLabel lblname1;
    private javax.swing.JLabel lblname2;
    private javax.swing.JLabel lblname3;
    private javax.swing.JLabel lblslp1;
    private javax.swing.JLabel lblslp2;
    private javax.swing.JLabel lblslp3;
    private javax.swing.JButton returnBtn;
    // End of variables declaration//GEN-END:variables
}
