/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

/**
 *
 * @author Suenlie
 */
public class Wakbalos extends javax.swing.JFrame {

    /**
     * Creates new form Wakbalos
     */
    public Wakbalos() {
        initComponents();
    }
    
    
    String name;
    int slp; 
    int count = 1;
    int stage;
    public Wakbalos(String name, int slp, int stage) {
        initComponents();
        this.stage = stage;
        this.name = name;
        this.slp = slp;
        lblBeast.setVisible(false);
        lblReptile.setVisible(false);
        prevBtn.setVisible(false);
        returnBtn.setBackground(new java.awt.Color(0,0,0,0));
        nextBtn.setBackground(new java.awt.Color(0,0,0,0));
        prevBtn.setBackground(new java.awt.Color(0,0,0,0));
        
    }

    public void wakbalos(){
        if(count == 1){
            lblAqua.setVisible(true);
            lblBeast.setVisible(false);
            lblReptile.setVisible(false);
            aqua.setVisible(true);
            beast.setVisible(false);
            reptile.setVisible(false);
            prevBtn.setVisible(false);
            nextBtn.setVisible(true);
        }else if(count == 2){
            lblAqua.setVisible(false);
            lblBeast.setVisible(true);
            lblReptile.setVisible(false);
            aqua.setVisible(false);
            beast.setVisible(true);
            reptile.setVisible(false);
            prevBtn.setVisible(true);
            nextBtn.setVisible(true);
        }else if(count == 3){
            lblAqua.setVisible(false);
            lblBeast.setVisible(false);
            lblReptile.setVisible(true);
            aqua.setVisible(false);
            beast.setVisible(false);
            reptile.setVisible(true);
            nextBtn.setVisible(false);
             prevBtn.setVisible(true);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReptile = new javax.swing.JLabel();
        lblBeast = new javax.swing.JLabel();
        lblAqua = new javax.swing.JLabel();
        returnBtn = new javax.swing.JButton();
        prevBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        aqua = new javax.swing.JLabel();
        beast = new javax.swing.JLabel();
        reptile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblReptile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/reptile-ezgif.com-resize.gif"))); // NOI18N
        getContentPane().add(lblReptile, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 130, 90));

        lblBeast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/beastfinal (1).gif"))); // NOI18N
        getContentPane().add(lblBeast, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 170, 110));

        lblAqua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/aquafinels.gif"))); // NOI18N
        getContentPane().add(lblAqua, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 170, 130));

        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });
        getContentPane().add(returnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));

        prevBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevBtnActionPerformed(evt);
            }
        });
        getContentPane().add(prevBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 70, 80));

        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        getContentPane().add(nextBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 70, 80));

        aqua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/AQUA.png"))); // NOI18N
        getContentPane().add(aqua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        beast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/beast (2).png"))); // NOI18N
        getContentPane().add(beast, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        reptile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/reptile.png"))); // NOI18N
        getContentPane().add(reptile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
        new Dashboard(name,slp,stage).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
        count++;
        wakbalos();
        
    }//GEN-LAST:event_nextBtnActionPerformed

    private void prevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevBtnActionPerformed
        // TODO add your handling code here:
        count--;
        wakbalos();
    }//GEN-LAST:event_prevBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wakbalos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wakbalos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wakbalos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wakbalos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wakbalos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aqua;
    private javax.swing.JLabel beast;
    private javax.swing.JLabel lblAqua;
    private javax.swing.JLabel lblBeast;
    private javax.swing.JLabel lblReptile;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton prevBtn;
    private javax.swing.JLabel reptile;
    private javax.swing.JButton returnBtn;
    // End of variables declaration//GEN-END:variables
}
